# ==========================================
# 1. Build React + prepare Spring Boot
# ==========================================
FROM node:22-alpine AS frontend-build

WORKDIR /app

# Copy React project
COPY frontend ./frontend

WORKDIR /app/frontend

# Install dependencies
RUN npm ci

# This runs:
# vite build
# + copies dist -> Spring Boot static folder
RUN npm run build


# ==========================================
# 2. Build Spring Boot
# ==========================================
FROM maven:3.9-eclipse-temurin-21 AS backend-build

WORKDIR /app

# Copy Spring Boot project
COPY pom.xml .
COPY src ./src

# Copy React production build generated by npm run build
COPY --from=frontend-build \
    /app/src/main/resources/static \
    ./src/main/resources/static

# Build Spring Boot JAR
RUN mvn clean package -DskipTests


# ==========================================
# 3. Production runtime
# ==========================================
FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

COPY --from=backend-build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
